--- #YAML:1.0
name:               Parse-Snort
version:            0.6
abstract:           Parse and create Snort rules
author:
    - Richard <perl-cpan@richardharman.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:             0
    Class::Accessor:  0
    List::Util:       0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
