--- #YAML:1.0
name:                Parse-Snort
version:             0.5
abstract:            Parse and create Snort rules
license:             ~
author:              
    - Richard <perl-cpan@richardharman.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Class::Accessor:               0
    List::Util:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
